name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for gh-pages deployment
      pages: write      # Required for GitHub Pages
      id-token: write   # Required for GitHub Pages

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: cargo doc --no-deps --features without-llvm -- --extend-css ./docs/docs.css

    - name: Glue in an index
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=xarxocore\">" > target/doc/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided
        publish_dir: ./target/doc
